// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPasswordEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPasswordEntry'](arg1, arg2, arg3);
}

export function CheckMasterPassword(arg1) {
  return window['go']['main']['App']['CheckMasterPassword'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function Drop() {
  return window['go']['main']['App']['Drop']();
}

export function GetAllEntries() {
  return window['go']['main']['App']['GetAllEntries']();
}

export function GetEntryById(arg1) {
  return window['go']['main']['App']['GetEntryById'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetMasterPassword() {
  return window['go']['main']['App']['GetMasterPassword']();
}

export function GetPasswordCount() {
  return window['go']['main']['App']['GetPasswordCount']();
}

export function GetRepositoryTag() {
  return window['go']['main']['App']['GetRepositoryTag']();
}

export function SaveLanguage(arg1) {
  return window['go']['main']['App']['SaveLanguage'](arg1);
}

export function SaveMasterPassword(arg1) {
  return window['go']['main']['App']['SaveMasterPassword'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
